### PR TITLE
Add m4tthumphrey/php-gitlab-api 11.x compatability

### PR DESCRIPTION
**Pull request by joshmiller83**

### CODE REVIEW

**Comment by joshmiller83** [comment]
Related to Issue #19

**Comment by Zeichen32** [comment]
We should create a new major version for this, because of some breaking changes between 10 and 11.
Can you only add ^11.2 for this new version?

**Comment by GrahamCampbell** [comment]
New major version is better IMO. Can just use `^11.0` probably. In fact, in the readme upstream, I tell people to install `^6.0` of this package. ;)

**Comment by GrahamCampbell** [comment]
https://github.com/GitLabPHP/Client#symfony

**Comment by joshmiller83** [comment]
Ok, just updated the version ... I guess it would be up to @Zeichen32 to roll a new 6.x release (I doubt we can pull request a release)...

I must say I'm very impressed with how responsive you all are and very much appreciate the work you're both doing in open source. Thank you :) 🎉

**Comment by GrahamCampbell** [comment]
You will also need tp bump the branch alias in the composer.json, as part of this PR. :)

**Comment by GrahamCampbell** [comment]
And also the readme needs updating with the correct install instructions.

**Comment by Zeichen32** [comment]
@joshmiller83 @GrahamCampbell Thanks for your contribution. I will merge this PR this weekend and release a new version!

**Pull request merged**
