### PR TITLE
Avoid deprecated create method

### LINKED ISSUE #10: Deprecated Code
Line 97 of `Zeichen32GitLabApiExtension.php` calls the deprecated `create` method:

```
            $definition->setFactory(array('Gitlab\Client', 'create'));
```

Instead, `new Client` should be used, followed by a call to `setUrl`.

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Closes #10.

### CODE REVIEW

**Comment by Zeichen32** [comment]
Can you fix the tests?
https://travis-ci.org/github/Zeichen32/GitLabApiBundle/jobs/708659790

**Comment by GrahamCampbell** [comment]
I'm unlikely to have time to do this in the near future (indeed, I don't actually use this package, but I do maintain the co-upstream package). It is likely a small job though, so if anyone who does use this library would like to contribute, that'd be great.

NB This change will really be needed when the next major version of the library is tagged (less than a month away), since it will block upgrading.

**Comment by Zeichen32** [comment]
No problem, i can do this. 👍

**Comment by Zeichen32** [comment]
Closing in favor of #14

**Pull request closed without merging**
