### PR TITLE
Update version

### PR DESCRIPTION
**Pull request by 20uf**
Hello,

Updated on the latest version.

Regards,

### CODE REVIEW

**Comment by violuke** [comment]
I'd also like this update

**Comment by Zeichen32** [comment]
Hey, sorry for the delay. I will accept the PR and the end of the day.

**Comment by Zeichen32** [comment]
@20uf and @violuke Ive updated the unit tests and fix the travis builds. You can use tagged version 3.0.0 to use the changes in this pr.

**Comment by 20uf** [comment]
Great, thanks !

**Pull request merged**
